import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { CreditPackageCard, PricingCard } from '@/components/pricing/pricing-cards';
import { Button } from '@/components/ui/button';
import { CREDIT_PACKAGES, PRICING_PLANS } from '@/lib/pricing';

export default function PricingPage() {
  return <main><section className="landing-shell pb-20 pt-24 text-center"><p className="eyebrow justify-center text-terracotta">Pricing</p><h1 className="mx-auto mt-6 max-w-5xl font-serif text-[clamp(4rem,9vw,8rem)] leading-[.82] tracking-[-.06em]">A plan for every creative rhythm.</h1><p className="mx-auto mt-8 max-w-xl text-base leading-7 text-stone-600">Choose monthly credits or add a one-time top-up through secure Stripe Checkout.</p></section><section className="landing-shell grid gap-5 pb-28 lg:grid-cols-3">{PRICING_PLANS.map((plan, index) => <PricingCard key={plan.id} choice={plan} featured={index === 1} />)}</section><section className="bg-[#ddd2c1] py-24"><div className="landing-shell"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Flexible top-ups</p><h2 className="section-title mt-5">Add credits when a project grows.</h2><p className="mt-6 max-w-md text-sm leading-6 text-stone-600">One-time packages fund the same organization credit balance used by Studio generations.</p></div><div className="grid gap-3 sm:grid-cols-2">{CREDIT_PACKAGES.map((item) => <CreditPackageCard key={item.id} choice={item} />)}</div></div></div></section><section className="landing-shell py-28"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">What credits get you</p><h2 className="section-title mt-5">One balance across the toolkit.</h2></div><div className="divide-y divide-stone-300 border-y border-stone-300">{['Virtual Try-On', 'AI Model', 'Photoshoot', 'Fashion Video'].map((tool, index) => <div key={tool} className="flex items-center justify-between py-6"><span className="font-serif text-2xl">{tool}</span><span className="text-xs text-stone-500">{index === 0 ? 'Cost varies by quality and outputs' : 'Coming soon · Cost to be finalized'}</span></div>)}</div></div></section><section className="bg-[#1b1c19] py-24 text-center text-white"><h2 className="mx-auto max-w-4xl font-serif text-6xl leading-none tracking-[-.05em]">Enter the Studio before choosing a plan.</h2><p className="mx-auto mt-6 max-w-lg text-sm leading-6 text-stone-400">Explore tools, upload assets, and understand the workflow first.</p><Button asChild className="mt-8 bg-white text-stone-950 hover:bg-[#bd7252]"><Link href="/studio">Open Studio <ArrowUpRight className="ml-2" size={16} /></Link></Button></section></main>;
}
